[package]
name = "music-discord-rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
discord-rich-presence = "1.0.0"
io = "0.0.2"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
urlencoding = "2.1"

